version: '3'
services:
  ranger-build:
    build:
      context: .
      dockerfile: Dockerfile.ranger-build
    image: ranger-build
    container_name: ranger-build
    hostname: ranger-build.example.com
    networks:
      - ranger
    volumes:
      # SELinux
      # https://github.com/moby/moby/issues/41202#issuecomment-657422171
      - m2:/home/ranger/.m2:Z
      - ./scripts:/home/ranger/scripts
      - ./patches:/home/ranger/patches
      - dist:/home/ranger/dist:Z
      - target:/home/ranger/target:Z
      # mount from host project root to container's project root
      - ${RANGER_HOME:-./../../}:/home/ranger/src:Z
    depends_on:
      - ranger-base
    environment:
      - BRANCH
      - BUILD_HOST_SRC
      - PROFILE
      - GIT_URL
      - RANGER_VERSION
      - SKIPTESTS

networks:
  ranger:
    name: rangernw

volumes:
  m2:
  dist:
  target:
